version: '3'

tasks:
  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}
    vars:
      PWD:
        sh: echo '$(pwd)'

  profiler:build:
    cmds:
      - go run .

  profiler:show:
    cmds:
      - go tool pprof main.go prof.prof
